version: 0.2

phases:
  install:
    commands:
      - echo "Restoring Terraform from cache..."
      - terraform --version || (sudo apt update && sudo apt install -y terraform)
  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
  build:
    commands:
      - echo "Applying Terraform plan..."
      - terraform apply -input=false tfplan

artifacts:
  files:
    - apply_output.log

cache:
  paths:
    - /usr/bin/terraform
    - /usr/share/keyrings/hashicorp-archive-keyring.gpg
