version: 0.2

phases:
  install:
    commands:
      - export release=AmazonLinux
      - dnf install -y dnf-plugins-core
      - dnf config-manager --add-repo https://rpm.releases.hashicorp.com/$release/hashicorp.repo
      - dnf install -y terraform
  build:
    commands:
      - terraform init
      - terraform init -reconfigure
      - terraform fmt
      - terraform fmt -check
      - terraform plan -input=false -out=tfplan
artifacts:
  files:
    - tfplan
